### ISSUE TITLE
Applying to class

### ISSUE THREAD

**Issue by morganzysman** [panorama-ed/maximize-select2-height#10]
Hi,

I have a few select2 on a single page all using the same classe, I wanted to know if I can maximize all the inputs at once using maximizeSelect2Height()?

Thank you,

Morgan

**Comment by JacobEvelyn** [comment]
Hi @morganzysman,

Yep, this should work fine, with something like `$(".your-class").maximizeSelect2Height();`. Please let us know if you have any problems!

Best,
Jacob
