### ISSUE TITLE
Mobile address bar causes issues

### ISSUE THREAD

**Issue by jmkristofzski** [panorama-ed/maximize-select2-height#13]
Everything works as intended if the mobile address bar is already showing when a longer select2 field is highlighted.

However, if a select2 field is highlighted when the address bar is hidden (typically happens automatically when scrolling down in Chrome for Android) then both the keyboard and address bar comes up. Once a query is typed in, the select2 height is set assuming there is no address bar, and goes off the screen as a result.

I guess one resolution would be adding cushion to the bottom with the available options if this plugin, however I don't think this is ideal.

**Comment by JacobEvelyn** [comment]
Thanks for letting us know. I'm not sure I have a good way to test this on mobile, but if you'd be willing to dig in and make a pull request I'd be happy to help, @jmkristofzski !

**Comment by jmkristofzski** [comment]
I think I've found a solution, but I'm not very familiar with making pull requests:

Replace "window.innerHeight"
with "window.document.documentElement.clientHeight"

I'm unsure if there are any issues with this approach, but I didn't notice any during my testing.

**Comment by JacobEvelyn** [comment]
Hey @jmkristofzski! Thanks for the code. This has been updated in version 1.0.3. Try it out and let us know if it fixes your issue!

**Comment by jmkristofzski** [comment]
It all seems to be working as intended now, thanks!
