### ISSUE TITLE
mousewheel not scrolling "up" reliably

### ISSUE THREAD

**Issue by halindrome** [panorama-ed/maximize-select2-height#18]
I have a relatively complex form with many select2 fields.   Maximize is really helping!  Unfortunately, I find myself in a situation where, from time to time, the mousewheel 'up' events seem to be ignored.   I don't know if this is a maximize issue, a select2 issue, or a jquery issue.  Thoughts?

P.S.  We are, for a variety of reasons, using jQuery 1.10.2

**Comment by JacobEvelyn** [comment]
Hey @halindrome! Glad you're finding this package helpful, and sorry to hear about the mousewheel issues! I haven't been able to reproduce this on my end... would you be able to send us a CodePen or something similar that demonstrates what you're seeing?

**Comment by JacobEvelyn** [comment]
I'm going to close this out. This package isn't doing anything that should impact mousewheel events at all—if you're still having issues I believe they'd either be with select2 or jQuery. Thanks!
