### ISSUE TITLE
TypeError: $(...)

### ISSUE THREAD

**Issue by gregh3269** [panorama-ed/maximize-select2-height#20]
Hello,

If there is not enough space below select2 will prompt above the input box (multiple), then there is an error in the log:

TypeError: $(...).parent(...).parent(...).parent(...).offset(...) is undefined
maximize-select2-height.js:85:52

widgetBoxOffset = $("#select2-" + id + "-container").
                        parent().parent().parent().offset().top;

**Comment by JacobEvelyn** [comment]
Hey @gregh3269! Thanks for opening this ticket, and sorry for the delay. I'm not able to reproduce this. Are you sure that your `id` is correct? Would you be able to make a JSFiddle to reproduce the error?

Thanks!

**Comment by gregh3269** [comment]
I cannot remember now how I originally spotted the error message, but to reproduce it :
In ff,  open the web console and expand it to just below the search field, then click on the field.  The "Please enter 2 or more characters" will show above the search field, and dump the error in the console.

**Comment by JacobEvelyn** [comment]
Sorry @gregh3269, I still can't reproduce the error you're seeing (using the `test.html` page in this repo). Could you make a JSFiddle or send a screenshot?

**Comment by gregh3269** [comment]
![Screenshot from 2020-02-04 16-30-13](https://user-images.githubusercontent.com/3933367/73765050-e78be800-476b-11ea-9d96-761ed6bc2e9a.png)
It needs to open above the select box.

**Comment by JacobEvelyn** [comment]
Hey @gregh3269! I'm still not able to reproduce what you're describing. Here's the code I tried:

```
<html>
  <head>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.min.js"></script>
    <style>
      html, body, select {
        font-family: sans-serif;
        font-size: 18px;
        line-height: 18px;

        padding-left: 10px;
        margin-left: 0;
      }

      body {
        /*width: 100%;*/ /* Uncomment for horizontal scrollbar (see README). */
        background-color: #F1EDC2;
      }
    </style>
  </head>
  <body>
    <div style="position: absolute; top: 600px; left: 200px">
      <!-- This should be maximized with the id selector -->
      <select id="test_thing_1" style="width: 200px">
      </select>
    </div>

    <script>
      // maximize-select2-height v1.0.3
      // (c) Panorama Education 2018
      // MIT License
      !function(t){"use strict"
      var e=t(window),n=t(document),o=function(o,i){return t.extend({cushion:i&&n.width()>e.width()?30:10},o)},i=function(n,i,c,r,s){var u,h,l
      return s?u=window.document.documentElement.clientHeight+e.scrollTop()-i.offset().top:(l=t("#select2-"+n+"-container").parent().parent().parent().offset().top,h=c.height()-i.height(),u=l-e.scrollTop()-h),u-o(r,s).cushion}
      t.fn.maximizeSelect2Height=function(e){return this.each(function(n,o){t(o).on("select2:open",function(){setTimeout(function(){var n=t("#select2-"+o.id+"-results"),c=n.parent(),r=c.parent(),s=r.hasClass("select2-dropdown--below"),u=i(o.id,n,r,e,s)
      c.css("max-height",u),n.css("max-height",u),t(document).trigger("scroll")})})})}}(jQuery)

      $(function () {
        $("#test_thing_1").select2({
          minimumInputLength: 2,
          ajax: {
            url: "https://jsonplaceholder.typicode.com/todos",
            processResults: function (data) {
              return {
                results: data.map((d) => {
                  return {
                    id: d.id,
                    text: d.title
                  }
                })
              };
            }
          }
        }).maximizeSelect2Height();
      });
    </script>
  </body>
</html>
```

And here's what I'm seeing (note that I did not bother to make the search functionality actually filter its results based on the search term):

<img width="1440" alt="Screen Shot 2020-02-11 at 1 26 31 PM" src="https://user-images.githubusercontent.com/1114569/74266544-75b71f80-4cd2-11ea-91dc-5966335542c0.png">
<img width="1440" alt="Screen Shot 2020-02-11 at 1 26 40 PM" src="https://user-images.githubusercontent.com/1114569/74266547-78197980-4cd2-11ea-93f5-4e14c356a635.png">
<img width="1440" alt="Screen Shot 2020-02-11 at 1 26 51 PM" src="https://user-images.githubusercontent.com/1114569/74266549-78b21000-4cd2-11ea-9bbb-3326b5ba879b.png">
<img width="1440" alt="Screen Shot 2020-02-11 at 1 27 19 PM" src="https://user-images.githubusercontent.com/1114569/74266551-794aa680-4cd2-11ea-8c33-00071a26d49f.png">

What am I missing? Also, what versions of `select2` and `maximize-select2-height` are you using?

**Comment by gregh3269** [comment]
OK, from your example add  multiple: true,

 $("#test_thing_1").select2({
          multiple: true,  <-------------------------------------------------------------
          minimumInputLength: 2,
          ajax: {..}
}).maximizeSelect2Height();

![Screenshot from 2020-02-12 16-03-06](https://user-images.githubusercontent.com/3933367/74353312-a28e3400-4db1-11ea-8936-ca16c307d74f.png)

It does not affect the plugin, it is just an ugly message.  
Cheers Greg

**Comment by JacobEvelyn** [comment]
Ah, thanks for the explanation @gregh3269! I'm working on a fix!

**Comment by JacobEvelyn** [comment]
@gregh3269 I think we've just fixed your issue in version 1.0.4. Update `maximize-select2-height` and let us know if you're still seeing the bug!

**Comment by gregh3269** [comment]
Looks good for me, many thanks.

**Comment by JacobEvelyn** [comment]
Awesome! Thanks so much for your patience in reporting this.
