### ISSUE TITLE
3.5.1 Support

### ISSUE THREAD

**Issue by Uptown76** [panorama-ed/maximize-select2-height#3]
Any chance getting this working for v3.5.1?

Thanks

**Comment by JacobEvelyn** [comment]
Great question! I think @honigc was interested in looking into that?

**Comment by elmart** [comment]
I have to suppose then that 4.0.x is not supported, either?
Would be nice if you advertised on home page which Select2 versions are supported.
Thx anyway

**Comment by JacobEvelyn** [comment]
@elmart great question; this is actually *only* written for Select2 v4. I'll change that on the README; thanks for the suggestion.

**Comment by elmart** [comment]
Great. Thanks :+1:

**Comment by JacobEvelyn** [comment]
@Uptown76 as we don't use earlier versions of Select2 for our applications and @honigc hasn't gotten a chance to look into this, I suspect we won't ourselves work to support any pre-4.0.0 versions of Select2, though we'd definitely welcome pull requests to add support for other versions.

I'm closing this for now, but do feel free to submit a pull request to add this support!
