### ISSUE TITLE
I have error with OffsetTOP

### ISSUE THREAD

**Issue by foRsxs** [panorama-ed/maximize-select2-height#9]
Hi! pls help, i have error
Uncaught TypeError: Cannot read property 'top' of undefined(…)

How to fix it?

**Comment by JacobEvelyn** [comment]
That error happens when whatever you're looking for on the page (probably with jQuery) doesn't exist. Could you share some more code?

**Comment by foRsxs** [comment]
Yes, i'am understand that element doesn't exist, but select2 element working. Which part of code need to share?

**Comment by foRsxs** [comment]
i found problem. Element Select2 must have id. My element works without it, and function computeMaxHeight send null Id.

**Comment by JacobEvelyn** [comment]
Glad you figured it out!

**Comment by morganzysman** [comment]
Thank you so much for the info! I had the same issue

**Comment by JacobEvelyn** [comment]
@foRsxs @morganzysman this is kind of buried at the bottom of the README. Feel free to submit a Pull Request to make it more noticeable!
